# Generated by Django 3.0.4 on 2020-03-27 13:15

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address_line_one', models.CharField(max_length=128)),
                ('address_line_two', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', phone_field.models.PhoneField(blank=True, help_text='Contact Phone Number', max_length=31)),
                ('notes', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('address_line_one', models.CharField(max_length=128)),
                ('address_line_two', models.CharField(blank=True, max_length=128)),
                ('zip_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=128)),
                ('mortgage_start_date', models.DateField()),
                ('mortgage_end_date', models.DateField()),
                ('mortgage', models.IntegerField()),
                ('mortgage_payment', models.IntegerField()),
                ('lease_space', models.ManyToManyField(related_name='lease_spaces', to='finance.LeaseSpace')),
                ('tenant', models.ManyToManyField(related_name='tenants', to='finance.Tenant')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Category')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Property')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Property'),
        ),
    ]
