# Generated by Django 3.0.4 on 2020-03-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='lease_space',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tenant',
        ),
    ]
