# Generated by Django 3.0.4 on 2020-03-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200327_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address_line_one',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address_line_two',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='mortgage',
        ),
        migrations.RemoveField(
            model_name='property',
            name='mortgage_end_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='mortgage_payment',
        ),
        migrations.RemoveField(
            model_name='property',
            name='mortgage_start_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='property',
            name='budget',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
