# Generated by Django 3.0.4 on 2020-03-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20200327_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='note',
        ),
        migrations.AddField(
            model_name='property',
            name='note',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
