# Generated by Django 3.0.4 on 2020-03-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20200327_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
