# Generated by Django 5.0.6 on 2024-07-04 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('case_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KitchenWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=6, unique=True)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=6, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=6, unique=True)),
                ('ship_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitchenBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=4, unique=True)),
                ('quantity_produced', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.finishedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='QASpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.TextField()),
                ('test_result', models.CharField(blank=True, max_length=255)),
                ('passed', models.BooleanField(default=False)),
                ('po_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.purchaseorder')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.FloatField()),
                ('quantity_received', models.FloatField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.purchaseorder')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.rawmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='raw_materials',
            field=models.ManyToManyField(through='inventory_management.PurchaseOrderDetail', to='inventory_management.rawmaterial'),
        ),
        migrations.CreateModel(
            name='KitchenWorkOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_allocated', models.FloatField()),
                ('kitchen_work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.kitchenworkorder')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.rawmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='kitchenworkorder',
            name='raw_materials',
            field=models.ManyToManyField(through='inventory_management.KitchenWorkOrderDetail', to='inventory_management.rawmaterial'),
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_date', models.DateField(auto_now_add=True)),
                ('quantity_adjusted', models.FloatField()),
                ('reason', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shipped', models.FloatField()),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.finishedproduct')),
                ('shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.shippingorder')),
            ],
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='finished_products',
            field=models.ManyToManyField(through='inventory_management.ShippingOrderDetail', to='inventory_management.finishedproduct'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.supplier'),
        ),
    ]
